[env]
SHELL = "/opt/homebrew/bin/fish"

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "--init-command", "tmux new-session -A -s main"]

[window]
option_as_alt = "Both"
decorations = "Full"
startup_mode = "Maximized"

[font]
size = 12.0
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
