theme  = "tokyonight_storm"

[editor]
cursorline = true
rulers = [81, 89, 121]
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
"0" = "goto_line_start"
"$" = "goto_line_end"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
"0" = "goto_line_start"
"$" = "goto_line_end"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
